django.request ERROR 2023-12-20 20:18:25,243 log 11829 139661556209344 Internal Server Error: /success/
Traceback (most recent call last):
  File "/home/emmy/Desktop/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmy/Desktop/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmy/Desktop/val_project/validationApp/views.py", line 33, in success
    return render(request, 'succes.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmy/Desktop/env/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmy/Desktop/env/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmy/Desktop/env/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: succes.html
django.server ERROR 2023-12-20 20:18:25,246 basehttp 11829 139661556209344 "GET /success/ HTTP/1.1" 500 86668
